function About() {
  const team = [
    { name: "Shashank Sanadhya", role: "Developer" },
    { name: "Uddhav Purohit", role: "Developer" },
    { name: "Sneha Paliwal", role: "Developer" },
    { name: "Saloni Choudhary", role: "Developer" },
  ];

  const features = [
    {
      icon: "🤖",
      title: "AI Powered",
      desc: "Smart travel plans generated by Artificial Intelligence.",
    },
    {
      icon: "🌍",
      title: "Explore Destinations",
      desc: "Discover curated travel guides across India.",
    },
    {
      icon: "💰",
      title: "Budget Planning",
      desc: "Smart breakdown of your travel expenses.",
    },
    {
      icon: "🌤️",
      title: "Live Weather",
      desc: "Real-time weather updates for your trip.",
    },
    {
      icon: "🗺️",
      title: "Interactive Maps",
      desc: "Explore destinations visually with maps.",
    },
    {
      icon: "📅",
      title: "Day-by-Day Plan",
      desc: "Automatic itinerary generation for your trip.",
    },
  ];

  const stats = [
    { number: "10K+", label: "Happy Travelers" },
    { number: "500+", label: "Destinations" },
    { number: "50K+", label: "Trips Planned" },
    { number: "4.9⭐", label: "User Rating" },
  ];

  return (
    <div className="min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-white transition-colors duration-300">

      {/* HERO */}
      <div
        className="relative h-[320px] bg-cover bg-center"
        style={{
          backgroundImage:
            "url('https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1600&q=80')",
        }}
      >
        <div className="absolute inset-0 bg-black/60" />

        <div className="relative z-10 flex flex-col items-center justify-center h-full text-center px-4">
          <h1 className="text-6xl font-black bg-gradient-to-r from-cyan-300 to-blue-400 bg-clip-text text-transparent">
            About Us ✈️
          </h1>

          <p className="text-white/90 mt-4 text-lg max-w-xl">
            We help you plan your dream trips with AI intelligence
          </p>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-8 py-14 space-y-12">

        {/* MISSION */}
        <div className="
          rounded-3xl p-8 text-center
          bg-white dark:bg-slate-900
          border border-slate-200 dark:border-slate-800
        ">
          <h2 className="text-3xl font-black mb-4">
            Our Mission 🎯
          </h2>

          <p className="text-slate-600 dark:text-slate-400 text-lg leading-relaxed max-w-3xl mx-auto">
            Travel AI makes trip planning simple, smart and affordable using Artificial Intelligence.
            We generate itineraries, budgets and travel insights automatically so you can enjoy more and plan less.
          </p>
        </div>

        {/* STATS */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {stats.map((s) => (
            <div
              key={s.label}
              className="
                rounded-2xl p-6 text-center
                bg-white dark:bg-slate-900
                border border-slate-200 dark:border-slate-800
                hover:-translate-y-1 transition-all
              "
            >
              <h2 className="text-4xl font-black bg-gradient-to-r from-cyan-500 to-blue-500 bg-clip-text text-transparent">
                {s.number}
              </h2>
              <p className="text-slate-500 dark:text-slate-400 mt-2 font-medium">
                {s.label}
              </p>
            </div>
          ))}
        </div>

        {/* FEATURES */}
        <div>
          <h2 className="text-3xl font-black text-center mb-8">
            What We Offer 🚀
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
            {features.map((f) => (
              <div
                key={f.title}
                className="
                  rounded-2xl p-6
                  bg-white dark:bg-slate-900
                  border border-slate-200 dark:border-slate-800
                  hover:-translate-y-1 transition-all
                "
              >
                <span className="text-4xl">{f.icon}</span>

                <h3 className="text-xl font-black mt-3">{f.title}</h3>

                <p className="text-slate-500 dark:text-slate-400 mt-2 text-sm leading-relaxed">
                  {f.desc}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* TEAM */}
        <div>
          <h2 className="text-3xl font-black text-center mb-8">
            Meet The Team 👨‍💻
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {team.map((m, i) => (
              <div
                key={i}
                className="
                  rounded-3xl p-6 text-center
                  bg-white dark:bg-slate-900
                  border border-slate-200 dark:border-slate-800
                  hover:-translate-y-1 transition-all
                "
              >
                <div className="w-24 h-24 mx-auto rounded-full bg-gradient-to-br from-cyan-500 to-blue-500 flex items-center justify-center text-3xl">
                  👤
                </div>

                <h3 className="text-xl font-black mt-4">{m.name}</h3>

                <p className="text-cyan-500 font-bold text-sm mt-1">
                  {m.role}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div className="
          rounded-3xl p-8 text-center
          bg-gradient-to-r from-cyan-50 to-blue-50
          dark:from-slate-900 dark:to-slate-900
          border border-blue-100 dark:border-slate-800
        ">
          <h2 className="text-3xl font-black">
            Ready to Explore? 🌍
          </h2>

          <p className="text-slate-600 dark:text-slate-400 mt-3">
            Start planning your dream trip with AI
          </p>

          <button
            onClick={() => (window.location.href = "/home")}
            className="
              mt-6 px-8 py-3 rounded-xl font-bold text-white
              bg-gradient-to-r from-cyan-500 to-blue-500
              hover:scale-105 transition-all
            "
          >
            Plan My Trip 🚀
          </button>
        </div>

      </div>
    </div>
  );
}

export default About;