function About() {
  const team = [
    {
      name: "Shashank Sanadhya",
      role: "Developer",
      image: "",
    },
    {
      name: "Uddhav Purohit",
      role: "Developer",
      image: "",
    },
    {
      name: "Sneha Paliwal",
      role: "Team Member",
      image: "Developer",
    },
    {
      name: "Saloni Choudhary",
      role: "Team Member",
      image: "Developer",
    },
  ];

  const features = [
    {
      icon: "🤖",
      title: "AI Powered",
      desc: "Smart travel plans generated by Artificial Intelligence based on your budget and preferences.",
    },
    {
      icon: "🌍",
      title: "Explore Destinations",
      desc: "Discover amazing places across India with curated travel guides and local tips.",
    },
    {
      icon: "💰",
      title: "Budget Planning",
      desc: "Smart budget breakdown for hotel, food, and travel so you never overspend.",
    },
    {
      icon: "🌤️",
      title: "Live Weather",
      desc: "Real-time weather updates for your destination to plan your trip perfectly.",
    },
    {
      icon: "🗺️",
      title: "Interactive Maps",
      desc: "Explore destinations with interactive maps and nearby attractions.",
    },
    {
      icon: "📅",
      title: "Day-by-Day Plan",
      desc: "Get a detailed day-by-day itinerary for your entire trip automatically.",
    },
  ];

  const stats = [
    { number: "10K+", label: "Happy Travelers" },
    { number: "500+", label: "Destinations" },
    { number: "50K+", label: "Trips Planned" },
    { number: "4.9⭐", label: "User Rating" },
  ];

  return (
    <div className="min-h-screen bg-white text-slate-900">
      {/* HERO SECTION */}
      <div
        className="relative h-[300px] bg-cover bg-center"
        style={{
          backgroundImage:
            "url('https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1600&q=80')",
        }}
      >
        <div className="absolute inset-0 bg-black/55" />

        <div className="relative z-10 flex flex-col items-center justify-center h-full text-center px-4">
          <h1 className="text-6xl font-black bg-gradient-to-r from-cyan-300 to-blue-400 bg-clip-text text-transparent">
            About Us ✈️
          </h1>

          <p className="text-white/90 mt-4 text-lg max-w-xl">
            We help you plan your dream trips with the power of AI
          </p>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-8 py-12">
        {/* MISSION */}
        <div className="bg-white rounded-3xl p-8 border border-slate-200 mb-10 text-center shadow-lg">
          <h2 className="text-3xl font-black mb-4 text-slate-900">
            Our Mission 🎯
          </h2>

          <p className="text-slate-600 text-lg leading-relaxed max-w-3xl mx-auto">
            Travel AI is built to make travel planning simple, smart, and
            affordable for everyone. Using the power of Artificial Intelligence,
            we create personalized itineraries, budget breakdowns, and
            destination guides — so you can focus on enjoying your journey, not
            planning it.
          </p>
        </div>

        {/* STATS */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {stats.map((stat, i) => (
            <div
              key={i}
              className="bg-white rounded-2xl p-6 text-center border border-slate-200 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300"
            >
              <h2 className="text-4xl font-black bg-gradient-to-r from-cyan-500 to-blue-500 bg-clip-text text-transparent">
                {stat.number}
              </h2>

              <p className="text-slate-500 mt-2 font-medium">{stat.label}</p>
            </div>
          ))}
        </div>

        {/* FEATURES */}
        <div className="mb-10">
          <h2 className="text-3xl font-black text-center mb-8 text-slate-900">
            What We Offer 🚀
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
            {features.map((f, i) => (
              <div
                key={i}
                className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300"
              >
                <span className="text-4xl">{f.icon}</span>

                <h3 className="text-xl font-black mt-3 text-slate-900">
                  {f.title}
                </h3>

                <p className="text-slate-500 mt-2 text-sm leading-relaxed">
                  {f.desc}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* TEAM */}
        <div className="mb-10">
          <h2 className="text-3xl font-black text-center mb-8 text-slate-900">
            Meet The Team 👨‍💻
          </h2>

          {/* First Row */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
            {team.slice(0, 2).map((member, i) => (
              <div
                key={i}
                className="bg-white rounded-3xl p-6 border border-slate-200 text-center shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300"
              >
                <div className="w-24 h-24 rounded-full mx-auto bg-gradient-to-br from-cyan-500 to-blue-500 flex items-center justify-center text-4xl shadow-lg">
                  👤
                </div>

                <h3 className="text-xl font-black mt-4 text-slate-900">
                  {member.name}
                </h3>

                <p className="text-cyan-600 text-sm mt-1 font-bold">
                  {member.role}
                </p>
              </div>
            ))}
          </div>

          {/* Second Row */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-2xl mx-auto">
            {team.slice(2, 4).map((member, i) => (
              <div
                key={i}
                className="bg-white rounded-3xl p-6 border border-slate-200 text-center shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300"
              >
                <div className="w-24 h-24 rounded-full mx-auto bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center text-4xl shadow-lg">
                  👤
                </div>

                <h3 className="text-xl font-black mt-4 text-slate-900">
                  {member.name}
                </h3>

                <p className="text-cyan-600 text-sm mt-1 font-bold">
                  {member.role}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div className="bg-gradient-to-r from-cyan-50 to-blue-50 rounded-3xl p-8 text-center border border-blue-100 shadow-sm">
          <h2 className="text-3xl font-black text-slate-900">
            Ready to Explore? 🌍
          </h2>

          <p className="text-slate-600 mt-3">
            Start planning your dream trip today with Travel AI
          </p>

          <button
            onClick={() => (window.location.href = "/home")}
            className="mt-6 bg-gradient-to-r from-cyan-500 to-blue-500 hover:scale-105 text-white px-8 py-3 rounded-xl font-bold transition-all shadow-lg shadow-cyan-500/25"
          >
            Plan My Trip 🚀
          </button>
        </div>
      </div>
    </div>
  );
}

export default About;