function About() {
  const team = [
    {
      name: "Shashank Sanadhya",
      role: "Full Stack Developer",
      image: "",
    },
    {
      name: "Uddhav Purohit",
      role: "Full Stack Developer",
      image: "",
    },
    {
      name: "Sneha Paliwal",
      role: "Nothing",
      image: "",
    },
    {
      name: "Saloni Choudhary",
      role: "Nothing",
      image: "",
    }
  ];

  const features = [
    {
      icon: "🤖",
      title: "AI Powered",
      desc: "Smart travel plans generated by Artificial Intelligence based on your budget and preferences."
    },
    {
      icon: "🌍",
      title: "Explore Destinations",
      desc: "Discover amazing places across India with curated travel guides and local tips."
    },
    {
      icon: "💰",
      title: "Budget Planning",
      desc: "Smart budget breakdown for hotel, food, and travel so you never overspend."
    },
    {
      icon: "🌤️",
      title: "Live Weather",
      desc: "Real-time weather updates for your destination to plan your trip perfectly."
    },
    {
      icon: "🗺️",
      title: "Interactive Maps",
      desc: "Explore destinations with interactive maps and nearby attractions."
    },
    {
      icon: "📅",
      title: "Day-by-Day Plan",
      desc: "Get a detailed day-by-day itinerary for your entire trip automatically."
    }
  ];

  const stats = [
    { number: "10K+", label: "Happy Travelers" },
    { number: "500+", label: "Destinations" },
    { number: "50K+", label: "Trips Planned" },
    { number: "4.9⭐", label: "User Rating" }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#071120] 
                    via-[#0a1b3d] to-[#09152a] text-white">

      {/* HERO SECTION */}
      <div className="relative h-[300px] bg-cover bg-center"
           style={{
             backgroundImage: "url('https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1600&q=80')"
           }}>
        <div className="absolute inset-0 bg-black/60" />
        <div className="relative z-10 flex flex-col items-center 
                        justify-center h-full text-center px-4">
          <h1 className="text-6xl font-bold bg-gradient-to-r from-blue-400 
                         to-cyan-400 bg-clip-text text-transparent">
            About Us ✈️
          </h1>
          <p className="text-gray-300 mt-4 text-lg max-w-xl">
            We help you plan your dream trips with the power of AI
          </p>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-8 py-12">

        {/* MISSION */}
        <div className="bg-white/10 backdrop-blur-lg rounded-3xl p-8 
                        border border-white/10 mb-10 text-center">
          <h2 className="text-3xl font-bold mb-4">Our Mission 🎯</h2>
          <p className="text-gray-300 text-lg leading-relaxed max-w-3xl mx-auto">
            Travel AI is built to make travel planning simple, smart, and affordable 
            for everyone. Using the power of Artificial Intelligence, we create 
            personalized itineraries, budget breakdowns, and destination guides — 
            so you can focus on enjoying your journey, not planning it.
          </p>
        </div>

        {/* STATS */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {stats.map((stat, i) => (
            <div key={i}
                 className="bg-white/10 backdrop-blur-lg rounded-2xl p-6 
                            text-center border border-white/10
                            hover:border-blue-500/50 hover:scale-105 
                            transition-all duration-300">
              <h2 className="text-4xl font-bold bg-gradient-to-r from-blue-400 
                             to-cyan-400 bg-clip-text text-transparent">
                {stat.number}
              </h2>
              <p className="text-gray-400 mt-2">{stat.label}</p>
            </div>
          ))}
        </div>

        {/* FEATURES */}
        <div className="mb-10">
          <h2 className="text-3xl font-bold text-center mb-8">
            What We Offer 🚀
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
            {features.map((f, i) => (
              <div key={i}
                   className="bg-white/10 backdrop-blur-lg rounded-2xl p-6
                              border border-white/10 hover:border-blue-500/50
                              hover:scale-105 transition-all duration-300">
                <span className="text-4xl">{f.icon}</span>
                <h3 className="text-xl font-bold mt-3">{f.title}</h3>
                <p className="text-gray-400 mt-2 text-sm leading-relaxed">
                  {f.desc}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* TEAM */}
        <div className="mb-10">
          <h2 className="text-3xl font-bold text-center mb-8">
            Meet The Team 👨‍💻
          </h2>

          {/* पहली Row — Shashank & Uddhav */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
            {team.slice(0, 2).map((member, i) => (
              <div key={i}
                   className="bg-white/10 backdrop-blur-lg rounded-3xl p-6
                              border border-white/10 text-center
                              hover:border-blue-500/50 hover:scale-105
                              transition-all duration-300">
                <div className="w-24 h-24 rounded-full mx-auto 
                                bg-gradient-to-br from-blue-500 to-cyan-500 
                                flex items-center justify-center text-4xl">
                  👤
                </div>
                <h3 className="text-xl font-bold mt-4">{member.name}</h3>
                <p className="text-blue-400 text-sm mt-1">{member.role}</p>
                <p className="text-gray-400 text-sm mt-2">{member.desc}</p>
              </div>
            ))}
          </div>

          {/* दूसरी Row — Sneha & Saloni Center में */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 
                          max-w-2xl mx-auto">
            {team.slice(2, 4).map((member, i) => (
              <div key={i}
                   className="bg-white/10 backdrop-blur-lg rounded-3xl p-6
                              border border-white/10 text-center
                              hover:border-blue-500/50 hover:scale-105
                              transition-all duration-300">
                <div className="w-24 h-24 rounded-full mx-auto 
                                bg-gradient-to-br from-purple-500 to-pink-500 
                                flex items-center justify-center text-4xl">
                  👤
                </div>
                <h3 className="text-xl font-bold mt-4">{member.name}</h3>
                <p className="text-blue-400 text-sm mt-1">{member.role}</p>
                <p className="text-gray-400 text-sm mt-2">{member.desc}</p>
              </div>
            ))}
          </div>

        </div>

        {/* CTA */}
        <div className="bg-gradient-to-r from-blue-600/30 to-cyan-600/30
                        rounded-3xl p-8 text-center border border-blue-500/20">
          <h2 className="text-3xl font-bold">
            Ready to Explore? 🌍
          </h2>
          <p className="text-gray-300 mt-3">
            Start planning your dream trip today with Travel AI
          </p>
          <button
            onClick={() => window.location.href = "/"}
            className="mt-6 bg-blue-500 hover:bg-blue-600 
                       px-8 py-3 rounded-xl font-bold
                       transition-all hover:shadow-lg 
                       hover:shadow-blue-500/30">
            Plan My Trip 🚀
          </button>
        </div>

      </div>
    </div>
  );
}

export default About;